package com.of.brm.mail.dto;

import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;

public class BillOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.op_trans_no
     *
     * @mbggenerated
     */
    private String opTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.dc_type
     *
     * @mbggenerated
     */
    private Integer dcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.pay_code
     *
     * @mbggenerated
     */
    private String payCode;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.auth_flag
     *
     * @mbggenerated
     */
    private String authFlag;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.verify_code_flag
     *
     * @mbggenerated
     */
    private String verifyCodeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.verify_code
     *
     * @mbggenerated
     */
    private String verifyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.order_amount
     *
     * @mbggenerated
     */
    private Double orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.fee_amount
     *
     * @mbggenerated
     */
    private Double feeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.order_type
     *
     * @mbggenerated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.device_type
     *
     * @mbggenerated
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.cur_code
     *
     * @mbggenerated
     */
    private Integer curCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.pay_channel
     *
     * @mbggenerated
     */
    private String payChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.complete_time
     *
     * @mbggenerated
     */
    private Date completeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;
    
    private Integer failedNum;
    
    private Integer payType;
    
    private String barCodes;
    
    private String amounts;
    
    private Double payAmount;
    
    public Double getPayAmount() {
		return payAmount;
	}

	public void setPayAmount(Double payAmount) {
		this.payAmount = payAmount;
	}

	public String getBarCodes() {
		return barCodes;
	}

	public void setBarCodes(String barCodes) {
		this.barCodes = barCodes;
	}

	public String getAmounts() {
		return amounts;
	}

	public void setAmounts(String amounts) {
		this.amounts = amounts;
	}

	public Integer getFailedNum() {
		return failedNum;
	}

	public void setFailedNum(Integer failedNum) {
		this.failedNum = failedNum;
	}

	public Integer getPayType() {
		return payType;
	}

	public void setPayType(Integer payType) {
		this.payType = payType;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.id
     *
     * @return the value of bill_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.id
     *
     * @param id the value for bill_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.order_no
     *
     * @return the value of bill_order.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.order_no
     *
     * @param orderNo the value for bill_order.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.user_id
     *
     * @return the value of bill_order.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.user_id
     *
     * @param userId the value for bill_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.op_trans_no
     *
     * @return the value of bill_order.op_trans_no
     *
     * @mbggenerated
     */
    public String getOpTransNo() {
        return opTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.op_trans_no
     *
     * @param opTransNo the value for bill_order.op_trans_no
     *
     * @mbggenerated
     */
    public void setOpTransNo(String opTransNo) {
        this.opTransNo = opTransNo == null ? null : opTransNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.dc_type
     *
     * @return the value of bill_order.dc_type
     *
     * @mbggenerated
     */
    public Integer getDcType() {
        return dcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.dc_type
     *
     * @param dcType the value for bill_order.dc_type
     *
     * @mbggenerated
     */
    public void setDcType(Integer dcType) {
        this.dcType = dcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.pay_code
     *
     * @return the value of bill_order.pay_code
     *
     * @mbggenerated
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.pay_code
     *
     * @param payCode the value for bill_order.pay_code
     *
     * @mbggenerated
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.auth_flag
     *
     * @return the value of bill_order.auth_flag
     *
     * @mbggenerated
     */
    public String getAuthFlag() {
		return authFlag;
	}
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.auth_flag
     *
     * @param payCode the value for bill_order.auth_flag
     *
     * @mbggenerated
     */
	public void setAuthFlag(String authFlag) {
		this.authFlag = authFlag;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.verify_code_flag
     *
     * @return the value of bill_order.verify_code_flag
     *
     * @mbggenerated
     */
    public String getVerifyCodeFlag() {
        return verifyCodeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.verify_code_flag
     *
     * @param verifyCodeFlag the value for bill_order.verify_code_flag
     *
     * @mbggenerated
     */
    public void setVerifyCodeFlag(String verifyCodeFlag) {
        this.verifyCodeFlag = verifyCodeFlag == null ? null : verifyCodeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.verify_code
     *
     * @return the value of bill_order.verify_code
     *
     * @mbggenerated
     */
    public String getVerifyCode() {
        return verifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.verify_code
     *
     * @param verifyCode the value for bill_order.verify_code
     *
     * @mbggenerated
     */
    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode == null ? null : verifyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.order_amount
     *
     * @return the value of bill_order.order_amount
     *
     * @mbggenerated
     */
    public Double getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.order_amount
     *
     * @param orderAmount the value for bill_order.order_amount
     *
     * @mbggenerated
     */
    public void setOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.fee_amount
     *
     * @return the value of bill_order.fee_amount
     *
     * @mbggenerated
     */
    public Double getFeeAmount() {
        return feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.fee_amount
     *
     * @param feeAmount the value for bill_order.fee_amount
     *
     * @mbggenerated
     */
    public void setFeeAmount(Double feeAmount) {
        this.feeAmount = feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.order_type
     *
     * @return the value of bill_order.order_type
     *
     * @mbggenerated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.order_type
     *
     * @param orderType the value for bill_order.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.device_type
     *
     * @return the value of bill_order.device_type
     *
     * @mbggenerated
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.device_type
     *
     * @param deviceType the value for bill_order.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.cur_code
     *
     * @return the value of bill_order.cur_code
     *
     * @mbggenerated
     */
    public Integer getCurCode() {
        return curCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.cur_code
     *
     * @param curCode the value for bill_order.cur_code
     *
     * @mbggenerated
     */
    public void setCurCode(Integer curCode) {
        this.curCode = curCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.pay_channel
     *
     * @return the value of bill_order.pay_channel
     *
     * @mbggenerated
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.pay_channel
     *
     * @param payChannel the value for bill_order.pay_channel
     *
     * @mbggenerated
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel == null ? null : payChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.order_status
     *
     * @return the value of bill_order.order_status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.order_status
     *
     * @param orderStatus the value for bill_order.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.complete_time
     *
     * @return the value of bill_order.complete_time
     *
     * @mbggenerated
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.complete_time
     *
     * @param completeTime the value for bill_order.complete_time
     *
     * @mbggenerated
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.create_time
     *
     * @return the value of bill_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.create_time
     *
     * @param createTime the value for bill_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.modify_time
     *
     * @return the value of bill_order.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.modify_time
     *
     * @param modifyTime the value for bill_order.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

	@Override
	public String toString() {
		return new ToStringBuilder(this).append("id", id)
				.append("orderNo", orderNo)
                .append("userId", userId)
                .append("opTransNo", opTransNo)
                .append("dcType", dcType)
                .append("payCode", payCode)
                .append("authFlag", authFlag)
                .append("verifyCodeFlag", verifyCodeFlag)
                .append("verifyCode", verifyCode)
                .append("orderAmount", orderAmount)
                .append("feeAmount", feeAmount)
                .append("orderType", orderType)
                .append("deviceType", deviceType)
                .append("curCode", curCode)
                .append("payChannel", payChannel)
                .append("orderStatus", orderStatus)
                .append("completeTime", completeTime)
                .append("createTime", createTime)
                .append("modifyTime", modifyTime)
                .append("failedNum", failedNum)
                .append("payType", payType).toString();
	}
}